version: "3.7"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  app:
    image: "oven/bun"
    container_name: weather-api-v1
    command: "bun run app.ts"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
