version: "3.7" 

services: 
  app: 
    image: "oven/bun" 
    container_name: weather-api-v1 
    command: "bun run app.ts" 
    volumes: 
      - .:/app
      - ./resolv.conf:/etc/resolv.conf
    working_dir: /app 
    ports: 
      - "3300:4100"
    networks: 
      home: 
        ipv4_address: 172.19.0.153 

networks: 
  home:
    external: true 
    name: my-dns
